// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Update")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e0dcfa80-9153-4688-911f-962b8481c4f1"),
                            Created = new DateTime(2025, 4, 28, 10, 14, 27, 938, DateTimeKind.Unspecified).AddTicks(6963),
                            Description = "Description test product 1",
                            Name = "Product 1",
                            Price = 20m,
                            Quantity = 100,
                            Update = new DateTime(2025, 4, 28, 10, 14, 27, 938, DateTimeKind.Unspecified).AddTicks(6963)
                        },
                        new
                        {
                            Id = new Guid("1ab8cc12-79ac-404d-aae8-d6a2886faf12"),
                            Created = new DateTime(2025, 4, 28, 10, 14, 27, 942, DateTimeKind.Unspecified).AddTicks(5506),
                            Description = "Description test product 2",
                            Name = "Product 2",
                            Price = 30m,
                            Quantity = 200,
                            Update = new DateTime(2025, 4, 28, 10, 14, 27, 942, DateTimeKind.Unspecified).AddTicks(5506)
                        },
                        new
                        {
                            Id = new Guid("5c1525d6-bc65-4a5b-98d3-4a08baad5ed2"),
                            Created = new DateTime(2025, 4, 28, 10, 14, 27, 942, DateTimeKind.Unspecified).AddTicks(5558),
                            Description = "Description test product 3",
                            Name = "Product 3",
                            Price = 40m,
                            Quantity = 300,
                            Update = new DateTime(2025, 4, 28, 10, 14, 27, 942, DateTimeKind.Unspecified).AddTicks(5558)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
